export const FETCH_WORKOUTS_SUCCESS = 'FETCH_WORKOUTS_SUCCESS'

export const FETCH_WORKOUTS_COMPLETE = 'FETCH_WORKOUTS_COMPLETE'

export const UPDATE_QUERY_STRING = 'UPDATE_QUERY_STRING'

export const SET_FILTER_TYPE = 'SET_FILTER_TYPE'

export const filterTypes = {
    WORKOUT_TITLE: 'WORKOUT_TITLE',
    BODY_PART: 'BODY_PART',
}

export const SET_ANCHOR = 'SET_ANCHOR'
